name: CI
on: [push]

jobs:
  deploy:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Push to server
        uses: appleboy/ssh-action@master
        with:
          python-version: '3.10'
          cache: 'pip'
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: cd ${{ secrets.DEV_PROJECT_PATH }} && git pull && source venv/bin/activate && pip install -r requirements.txt
      - run: python ci_cd_confirmation_script.py
